### ISSUE TITLE
上下平移动画体验不好

### ISSUE THREAD

**Issue by MrBoudar** [hanks-zyh/PhotoViewer#1]
上下平移动画体验不好，还有共享元素动画兼容问题，5.0之后才支持该动画.

**Comment by hanks-zyh** [comment]
@MrBoudar 能具体描述一下吗，支持5.0 一下的动画呀

**Comment by MrBoudar** [comment]
上下平移动画建议优化下，上下平移要考虑长图片这块的优化，其他的还好，我记得5.0之后才支持这个共享动画，5.0之下的用坐标来实现吧
